% первая волна
\filldraw[fill=yellow!40!white, draw=black,thick](0,1) rectangle (1,2);
\filldraw[fill=yellow!40!white, draw=black,thick](-1,1) rectangle (0,2);
\filldraw[fill=yellow!40!white, draw=black,thick](-1,0) rectangle (0,1);
\filldraw[fill=yellow!40!white, draw=black,thick](-1,-1) rectangle (0,0);
\filldraw[fill=yellow!40!white, draw=black,thick](0,-1) rectangle (1,0);
\filldraw[fill=yellow!40!white, draw=black,thick](1,-1) rectangle (2,0);
\filldraw[fill=yellow!40!white, draw=black,thick](1,0) rectangle (2,1);
